server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: config-server

---
spring:
  profiles:
    group:
      dev:
        - "native"
  cloud:
    config:
      server:
        native:
          search-locations:
            - "classpath:/conf"